export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const MAIL_AGGREGATE_REQUEST = 'MAIL_AGGREGATE_REQUEST';
export const MAIL_AGGREGATE_SUCCESS = 'MAIL_AGGREGATE_SUCCESS';
export const MAIL_AGGREGATE_FAILURE = 'MAIL_AGGREGATE_FAILURE';
export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST';
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE';
export const MARK_EMAIL_REQUEST = 'MARK_EMAIL_REQUEST';
export const MARK_EMAIL_SUCCESS = 'MARK_EMAIL_SUCCESS';
export const MARK_EMAIL_FAILURE = 'MARK_EMAIL_FAILURE';

export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
